In [2]:
from db import Database
import struct

In [3]:
t = Database("test.sqlite")


Database initialized.
vec_version(): 3.46.1
sqlite_version(): v0.1.3



In [5]:
t.create_tables()

In [6]:
res = t.get_last_entry()

In [7]:
def deserialize(serialized_data: bytes) -> list[float]:
    """deserializes raw bytes back into a list of floats"""
    num_floats = len(serialized_data) // struct.calcsize('f')  # number of floats
    return list(struct.unpack(f'{num_floats}f', serialized_data))

In [8]:
res[1]

'smarn_screenshots/mouse.jpg'

In [9]:
from vectors import get_img_emb
import numpy as np

In [10]:
get_img_emb("smarn_screenshots/mouse.jpg")

array([ 4.88567492e-03,  3.06329262e-02, -1.16505707e-02, -5.43707088e-02,
       -4.30433601e-02,  1.43875908e-02, -3.93362269e-02,  1.51968347e-02,
       -1.79930907e-02, -3.71160954e-02,  3.17983851e-02, -1.64869502e-02,
        1.66994240e-02,  1.74279232e-02, -3.26601341e-02, -2.96015176e-03,
        2.71845032e-02,  1.17709888e-02, -2.17663869e-02, -2.77326144e-02,
       -3.22495364e-02, -4.80828844e-02, -2.95029897e-02, -1.00016156e-02,
        1.79912262e-02, -1.32435909e-03,  8.80000554e-03, -2.18022894e-02,
        4.10039425e-02,  3.95343184e-01, -2.49706791e-04,  2.92185359e-02,
        1.00903166e-02, -1.61880118e-04, -6.91604521e-03,  6.92566484e-03,
       -4.93146814e-02, -3.90196070e-02,  2.23313812e-02, -7.03396834e-03,
       -1.73426028e-02,  3.06921676e-02, -2.93518342e-02, -2.66491156e-03,
        3.90557721e-02, -2.36145891e-02, -5.95984561e-03,  4.84663025e-02,
       -3.25033139e-03,  3.88304070e-02,  1.28255971e-02,  1.09729068e-02,
        4.37131710e-02,  

In [11]:
np.array(deserialize(res[0]))

array([ 4.88567492e-03,  3.06329262e-02, -1.16505707e-02, -5.43707088e-02,
       -4.30433601e-02,  1.43875908e-02, -3.93362269e-02,  1.51968347e-02,
       -1.79930907e-02, -3.71160954e-02,  3.17983851e-02, -1.64869502e-02,
        1.66994240e-02,  1.74279232e-02, -3.26601341e-02, -2.96015176e-03,
        2.71845032e-02,  1.17709888e-02, -2.17663869e-02, -2.77326144e-02,
       -3.22495364e-02, -4.80828844e-02, -2.95029897e-02, -1.00016156e-02,
        1.79912262e-02, -1.32435909e-03,  8.80000554e-03, -2.18022894e-02,
        4.10039425e-02,  3.95343184e-01, -2.49706791e-04,  2.92185359e-02,
        1.00903166e-02, -1.61880118e-04, -6.91604521e-03,  6.92566484e-03,
       -4.93146814e-02, -3.90196070e-02,  2.23313812e-02, -7.03396834e-03,
       -1.73426028e-02,  3.06921676e-02, -2.93518342e-02, -2.66491156e-03,
        3.90557721e-02, -2.36145891e-02, -5.95984561e-03,  4.84663025e-02,
       -3.25033139e-03,  3.88304070e-02,  1.28255971e-02,  1.09729068e-02,
        4.37131710e-02,  

In [5]:
t.insert_entry("smarn_screenshots/keeb.jpg")

In [6]:
t.insert_entry("smarn_screenshots/mob1.jpg")

In [7]:
t.get_last_entry()

(2, 'smarn_screenshots/mob1.jpg', '2024-10-07 06:23:32')

In [8]:
t.insert_entry("smarn_screenshots/mouse.jpg")

In [9]:
t.get_last_entry()

(3, 'smarn_screenshots/mouse.jpg', '2024-10-07 06:23:36')

In [4]:
from utils import *

In [12]:
compare_with_prev_img("smarn_screenshots/mouse.jpg")

(True,
 array([ 4.88567492e-03,  3.06329262e-02, -1.16505707e-02, -5.43707088e-02,
        -4.30433601e-02,  1.43875908e-02, -3.93362269e-02,  1.51968347e-02,
        -1.79930907e-02, -3.71160954e-02,  3.17983851e-02, -1.64869502e-02,
         1.66994240e-02,  1.74279232e-02, -3.26601341e-02, -2.96015176e-03,
         2.71845032e-02,  1.17709888e-02, -2.17663869e-02, -2.77326144e-02,
        -3.22495364e-02, -4.80828844e-02, -2.95029897e-02, -1.00016156e-02,
         1.79912262e-02, -1.32435909e-03,  8.80000554e-03, -2.18022894e-02,
         4.10039425e-02,  3.95343184e-01, -2.49706791e-04,  2.92185359e-02,
         1.00903166e-02, -1.61880118e-04, -6.91604521e-03,  6.92566484e-03,
        -4.93146814e-02, -3.90196070e-02,  2.23313812e-02, -7.03396834e-03,
        -1.73426028e-02,  3.06921676e-02, -2.93518342e-02, -2.66491156e-03,
         3.90557721e-02, -2.36145891e-02, -5.95984561e-03,  4.84663025e-02,
        -3.25033139e-03,  3.88304070e-02,  1.28255971e-02,  1.09729068e-02,
     

In [13]:
compare_with_prev_img("smarn_screenshots/keeb.jpg")

(False, None)